import type { Task, TaskRelation, Project } from '@/types';

export const INITIAL_LOCAL_PROJECTS: Project[] = [
  {
    id: 'proj-wujie-sso',
    name: 'SSO + WuJie 微前端工程架构开发',
    description: '基于无界 (WuJie) 极速微前端框架与统一认证中心的分布式企业级门户平台研发',
    color: '#3b82f6',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const now = new Date();
const d0 = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 9, 0);
const addDays = (d: Date, days: number) => {
  const res = new Date(d);
  res.setDate(res.getDate() + days);
  return res;
};

export const INITIAL_LOCAL_TASKS: Task[] = [
  {
    id: 'task-root',
    title: '微前端门户平台研发总工程',
    description: '微前端主基座、子应用集群与统一单点登录研发的顶级根任务',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    projectId: 'proj-wujie-sso',
    parentId: null,
    startAt: d0,
    endAt: addDays(d0, 30),
    isAllDay: false,
    estimatedDuration: 3600,
    actualDuration: null,
    sortOrder: 0,
    isDeleted: false,
    deletedAt: null,
    createdAt: d0,
    updatedAt: d0,
  },
  {
    id: 'task-sso-arch',
    title: '统一认证中心 SSO 架构方案设计',
    description: '梳理 CAS / OAuth2.0 / OIDC 认证流，设计跨域 Cookie 共享与 Token 静默刷新机制',
    status: 'DONE',
    priority: 'HIGH',
    projectId: 'proj-wujie-sso',
    parentId: 'task-root',
    startAt: d0,
    endAt: addDays(d0, 2),
    isAllDay: false,
    estimatedDuration: 480,
    actualDuration: 450,
    sortOrder: 1,
    isDeleted: false,
    deletedAt: null,
    createdAt: d0,
    updatedAt: d0,
  },
  {
    id: 'task-sso-service',
    title: 'SSO 认证网关与 Token 鉴权服务实现',
    description: '基于 JWT RS256 签名体系完成登录授权接口、单点登出广播与会话校验中间件',
    status: 'DONE',
    priority: 'HIGH',
    projectId: 'proj-wujie-sso',
    parentId: 'task-root',
    startAt: addDays(d0, 2),
    endAt: addDays(d0, 5),
    isAllDay: false,
    estimatedDuration: 600,
    actualDuration: 580,
    sortOrder: 2,
    isDeleted: false,
    deletedAt: null,
    createdAt: d0,
    updatedAt: d0,
  },
  {
    id: 'task-wujie-host',
    title: 'WuJie 微前端主基座宿主应用搭建',
    description: '搭建 React 19 基座，配置 WujieApp 容器组件，实现导航菜单与多标签页 Keep-Alive 保活机制',
    status: 'DONE',
    priority: 'HIGH',
    projectId: 'proj-wujie-sso',
    parentId: 'task-root',
    startAt: addDays(d0, 2),
    endAt: addDays(d0, 4),
    isAllDay: false,
    estimatedDuration: 480,
    actualDuration: 480,
    sortOrder: 3,
    isDeleted: false,
    deletedAt: null,
    createdAt: d0,
    updatedAt: d0,
  },
  {
    id: 'task-bus-protocol',
    title: 'WuJie 通信总线与全局状态代理封装',
    description: '封装 bus.emit/bus.on 通信协议规范，打通基座与子应用间的主题、用户状态与路由广播',
    status: 'DONE',
    priority: 'MEDIUM',
    projectId: 'proj-wujie-sso',
    parentId: 'task-root',
    startAt: addDays(d0, 4),
    endAt: addDays(d0, 6),
    isAllDay: false,
    estimatedDuration: 360,
    actualDuration: 300,
    sortOrder: 4,
    isDeleted: false,
    deletedAt: null,
    createdAt: d0,
    updatedAt: d0,
  },
  {
    id: 'task-sub-app-a',
    title: '子应用 A: 用户权限与组织管理中心改造接入',
    description: '改造旧版 Vue3 应用为无界微前端子应用，抽离独立入口，适配基座注入的 SSO Token',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    projectId: 'proj-wujie-sso',
    parentId: 'task-root',
    startAt: addDays(d0, 6),
    endAt: addDays(d0, 11),
    isAllDay: false,
    estimatedDuration: 720,
    actualDuration: null,
    sortOrder: 5,
    isDeleted: false,
    deletedAt: null,
    createdAt: d0,
    updatedAt: d0,
  },
  {
    id: 'task-sub-app-b',
    title: '子应用 B: 核心业务报表分析工作台改造接入',
    description: '改造 React 报表工作台子应用，集成基座数据下发总线与微前端沙箱代理',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    projectId: 'proj-wujie-sso',
    parentId: 'task-root',
    startAt: addDays(d0, 6),
    endAt: addDays(d0, 11),
    isAllDay: false,
    estimatedDuration: 720,
    actualDuration: null,
    sortOrder: 6,
    isDeleted: false,
    deletedAt: null,
    createdAt: d0,
    updatedAt: d0,
  },
  {
    id: 'task-integration',
    title: '跨子应用免登授权与路由同步联合调试',
    description: '联调基座与子应用间的免登录无感透传，修复浏览器前进后退与子应用 Hash/History 冲突',
    status: 'BLOCKED',
    priority: 'URGENT',
    projectId: 'proj-wujie-sso',
    parentId: 'task-root',
    startAt: addDays(d0, 11),
    endAt: addDays(d0, 15),
    isAllDay: false,
    estimatedDuration: 540,
    actualDuration: null,
    sortOrder: 7,
    isDeleted: false,
    deletedAt: null,
    createdAt: d0,
    updatedAt: d0,
  },
  {
    id: 'task-sandbox-test',
    title: 'WuJie 沙箱隔离、样式防穿透与内存泄漏压测',
    description: '压测长周期切换 100 次子应用的内存占用，验证 window 变量隔离与 CSS 样式完全防穿透',
    status: 'TODO',
    priority: 'MEDIUM',
    projectId: 'proj-wujie-sso',
    parentId: 'task-root',
    startAt: addDays(d0, 15),
    endAt: addDays(d0, 18),
    isAllDay: false,
    estimatedDuration: 420,
    actualDuration: null,
    sortOrder: 8,
    isDeleted: false,
    deletedAt: null,
    createdAt: d0,
    updatedAt: d0,
  },
  {
    id: 'task-deploy',
    title: '微前端集群容器化构建与 Nginx 反向代理部署',
    description: '编写 Docker 多阶段镜像构建脚本，配置 Nginx 跨域与子应用静态资源 CORS 头转发',
    status: 'TODO',
    priority: 'URGENT',
    projectId: 'proj-wujie-sso',
    parentId: 'task-root',
    startAt: addDays(d0, 18),
    endAt: addDays(d0, 22),
    isAllDay: false,
    estimatedDuration: 600,
    actualDuration: null,
    sortOrder: 9,
    isDeleted: false,
    deletedAt: null,
    createdAt: d0,
    updatedAt: d0,
  },
  {
    id: 'task-inbox-1',
    title: '调研 WuJie 预加载 preload 与保活 keep-alive 在低配置客户端的内存开销',
    description: '收件箱暂存任务，后续评估是否纳入正式压测技术方案中',
    status: 'INBOX',
    priority: 'MEDIUM',
    projectId: null,
    parentId: null,
    startAt: null,
    endAt: null,
    isAllDay: false,
    estimatedDuration: null,
    actualDuration: null,
    sortOrder: 0,
    isDeleted: false,
    deletedAt: null,
    createdAt: d0,
    updatedAt: d0,
  },
];

export const INITIAL_LOCAL_RELATIONS: TaskRelation[] = [
  {
    id: 'rel-1',
    sourceTaskId: 'task-sso-service',
    targetTaskId: 'task-sso-arch',
    relationType: 'DEPENDS_ON',
    description: 'SSO鉴权服务依赖整体认证架构设计',
    createdAt: d0,
  },
  {
    id: 'rel-2',
    sourceTaskId: 'task-wujie-host',
    targetTaskId: 'task-sso-arch',
    relationType: 'DEPENDS_ON',
    description: '基座搭建依赖全局认证与通信架构方案',
    createdAt: d0,
  },
  {
    id: 'rel-3',
    sourceTaskId: 'task-bus-protocol',
    targetTaskId: 'task-wujie-host',
    relationType: 'DEPENDS_ON',
    description: '通信协议封装依赖基座宿主运行容器',
    createdAt: d0,
  },
  {
    id: 'rel-4',
    sourceTaskId: 'task-sub-app-a',
    targetTaskId: 'task-sso-service',
    relationType: 'DEPENDS_ON',
    description: '用户权限中心改造依赖统一SSO Token规范',
    createdAt: d0,
  },
  {
    id: 'rel-5',
    sourceTaskId: 'task-sub-app-a',
    targetTaskId: 'task-bus-protocol',
    relationType: 'DEPENDS_ON',
    description: '用户权限中心依赖通信总线协议',
    createdAt: d0,
  },
  {
    id: 'rel-6',
    sourceTaskId: 'task-sub-app-b',
    targetTaskId: 'task-sso-service',
    relationType: 'DEPENDS_ON',
    description: '报表中心改造依赖统一SSO鉴权服务',
    createdAt: d0,
  },
  {
    id: 'rel-7',
    sourceTaskId: 'task-sub-app-b',
    targetTaskId: 'task-bus-protocol',
    relationType: 'DEPENDS_ON',
    description: '报表工作台依赖全局通信与事件总线',
    createdAt: d0,
  },
  {
    id: 'rel-8',
    sourceTaskId: 'task-integration',
    targetTaskId: 'task-sub-app-a',
    relationType: 'DEPENDS_ON',
    description: '跨应用联调必须等待子应用A改造完毕',
    createdAt: d0,
  },
  {
    id: 'rel-9',
    sourceTaskId: 'task-integration',
    targetTaskId: 'task-sub-app-b',
    relationType: 'DEPENDS_ON',
    description: '跨应用联调必须等待子应用B改造完毕',
    createdAt: d0,
  },
  {
    id: 'rel-10',
    sourceTaskId: 'task-sandbox-test',
    targetTaskId: 'task-integration',
    relationType: 'DEPENDS_ON',
    description: '沙箱稳定性压测必须等待联合调试打通',
    createdAt: d0,
  },
  {
    id: 'rel-11',
    sourceTaskId: 'task-deploy',
    targetTaskId: 'task-sandbox-test',
    relationType: 'DEPENDS_ON',
    description: '生产多环境发布必须在压测通过后进行',
    createdAt: d0,
  },
];
